"use strict";
const MAX_PHOTOS=4;
const state={photos:[],outerPadding:80,gap:24,backgroundColor:"#ffffff",canvasRatio:"1:1",fitMode:"cover",equalCells:true,roundedCorners:false,cornerRadius:24,exportFormat:"png",jpegQuality:96,exportLongEdge:"4000"};
const ui={fileInput:document.getElementById("fileInput"),photoSlots:document.getElementById("photoSlots"),clearAllButton:document.getElementById("clearAllButton"),outerPadding:document.getElementById("outerPadding"),outerPaddingValue:document.getElementById("outerPaddingValue"),gap:document.getElementById("gap"),gapValue:document.getElementById("gapValue"),backgroundColor:document.getElementById("backgroundColor"),backgroundColorText:document.getElementById("backgroundColorText"),canvasRatio:document.getElementById("canvasRatio"),fitMode:document.getElementById("fitMode"),equalCells:document.getElementById("equalCells"),roundedCorners:document.getElementById("roundedCorners"),cornerRadiusField:document.getElementById("cornerRadiusField"),cornerRadius:document.getElementById("cornerRadius"),cornerRadiusValue:document.getElementById("cornerRadiusValue"),exportFormat:document.getElementById("exportFormat"),exportLongEdge:document.getElementById("exportLongEdge"),jpegQualityField:document.getElementById("jpegQualityField"),jpegQuality:document.getElementById("jpegQuality"),jpegQualityValue:document.getElementById("jpegQualityValue"),downloadButton:document.getElementById("downloadButton"),demoButton:document.getElementById("demoButton"),dropZone:document.getElementById("dropZone"),emptyState:document.getElementById("emptyState"),previewCanvas:document.getElementById("previewCanvas"),outputInfo:document.getElementById("outputInfo")};
let draggedIndex=null;
function init(){renderSlots();bindEvents();renderPreview()}
function bindEvents(){ui.fileInput.addEventListener("change",e=>addFiles(e.target.files));ui.clearAllButton.addEventListener("click",clearAll);ui.outerPadding.addEventListener("input",()=>{state.outerPadding=+ui.outerPadding.value;ui.outerPaddingValue.textContent=`${state.outerPadding} px`;renderPreview()});ui.gap.addEventListener("input",()=>{state.gap=+ui.gap.value;ui.gapValue.textContent=`${state.gap} px`;renderPreview()});ui.backgroundColor.addEventListener("input",()=>setBackgroundColor(ui.backgroundColor.value));ui.backgroundColorText.addEventListener("input",()=>{const c=normalizeHex(ui.backgroundColorText.value);if(c)setBackgroundColor(c)});ui.backgroundColorText.addEventListener("blur",()=>ui.backgroundColorText.value=state.backgroundColor);ui.canvasRatio.addEventListener("change",()=>{state.canvasRatio=ui.canvasRatio.value;renderPreview()});ui.fitMode.addEventListener("change",()=>{state.fitMode=ui.fitMode.value;renderPreview()});ui.equalCells.addEventListener("change",()=>{state.equalCells=ui.equalCells.checked;renderPreview()});ui.roundedCorners.addEventListener("change",()=>{state.roundedCorners=ui.roundedCorners.checked;ui.cornerRadiusField.hidden=!state.roundedCorners;renderPreview()});ui.cornerRadius.addEventListener("input",()=>{state.cornerRadius=+ui.cornerRadius.value;ui.cornerRadiusValue.textContent=`${state.cornerRadius} px`;renderPreview()});ui.exportFormat.addEventListener("change",()=>{state.exportFormat=ui.exportFormat.value;ui.jpegQualityField.hidden=state.exportFormat!=="jpeg"});ui.jpegQuality.addEventListener("input",()=>{state.jpegQuality=+ui.jpegQuality.value;ui.jpegQualityValue.textContent=String(state.jpegQuality)});ui.exportLongEdge.addEventListener("change",()=>state.exportLongEdge=ui.exportLongEdge.value);ui.downloadButton.addEventListener("click",downloadCollage);ui.demoButton.addEventListener("click",loadDemo);["dragenter","dragover"].forEach(t=>ui.dropZone.addEventListener(t,e=>{e.preventDefault();ui.dropZone.classList.add("drag-active")}));["dragleave","drop"].forEach(t=>ui.dropZone.addEventListener(t,e=>{e.preventDefault();ui.dropZone.classList.remove("drag-active")}));ui.dropZone.addEventListener("drop",e=>addFiles(e.dataTransfer.files))}
async function addFiles(list){const remain=MAX_PHOTOS-state.photos.length;if(remain<=0)return;for(const file of [...list].filter(f=>f.type.startsWith("image/")).slice(0,remain)){try{const url=URL.createObjectURL(file);const image=await loadImage(url);state.photos.push({file,url,image,name:file.name,position:"center"})}catch(e){alert(`${file.name} を読み込めませんでした。`)}}ui.fileInput.value="";renderSlots();renderPreview()}
function loadImage(url){return new Promise((res,rej)=>{const i=new Image;i.onload=()=>res(i);i.onerror=rej;i.src=url})}
function clearAll(){state.photos.forEach(p=>URL.revokeObjectURL(p.url));state.photos=[];renderSlots();renderPreview()}
function removePhoto(i){const [p]=state.photos.splice(i,1);if(p)URL.revokeObjectURL(p.url);renderSlots();renderPreview()}
function movePhoto(i,d){const n=i+d;if(n<0||n>=state.photos.length)return;[state.photos[i],state.photos[n]]=[state.photos[n],state.photos[i]];renderSlots();renderPreview()}
function setBackgroundColor(v){state.backgroundColor=v;ui.backgroundColor.value=v;ui.backgroundColorText.value=v;renderPreview()}
function normalizeHex(v){let c=String(v||"").trim();if(!c.startsWith("#"))c=`#${c}`;return/^#[0-9a-fA-F]{6}$/.test(c)?c.toLowerCase():null}
function renderSlots(){ui.photoSlots.innerHTML="";for(let i=0;i<MAX_PHOTOS;i++){const p=state.photos[i],slot=document.createElement("article");slot.className="photo-slot";slot.draggable=!!p;slot.dataset.index=i;if(p){slot.innerHTML=`<div class="slot-preview"><img src="${p.url}" alt=""></div><div class="slot-copy"><div class="slot-title">${escapeHtml(p.name)}</div><div class="slot-sub">${p.image.naturalWidth} × ${p.image.naturalHeight}px</div><select class="position-select">${positionOptions(p.position)}</select></div><div class="slot-controls"><button class="slot-button" data-action="up">前へ</button><button class="slot-button" data-action="down">後へ</button><button class="slot-button" data-action="remove">削除</button></div>`;slot.querySelector(".position-select").addEventListener("change",e=>{p.position=e.target.value;renderPreview()});slot.querySelector('[data-action="up"]').addEventListener("click",()=>movePhoto(i,-1));slot.querySelector('[data-action="down"]').addEventListener("click",()=>movePhoto(i,1));slot.querySelector('[data-action="remove"]').addEventListener("click",()=>removePhoto(i));slot.addEventListener("dragstart",()=>{draggedIndex=i;slot.classList.add("dragging")});slot.addEventListener("dragend",()=>{draggedIndex=null;slot.classList.remove("dragging")});slot.addEventListener("dragover",e=>{e.preventDefault();slot.classList.add("drag-over")});slot.addEventListener("dragleave",()=>slot.classList.remove("drag-over"));slot.addEventListener("drop",e=>{e.preventDefault();slot.classList.remove("drag-over");if(draggedIndex===null||draggedIndex===i)return;const[m]=state.photos.splice(draggedIndex,1);state.photos.splice(i,0,m);draggedIndex=null;renderSlots();renderPreview()})}else{slot.innerHTML=`<div class="slot-preview">${i+1}</div><div class="slot-copy"><div class="slot-title">写真 ${i+1}</div><div class="slot-sub">未選択</div></div>`}ui.photoSlots.appendChild(slot)}ui.downloadButton.disabled=state.photos.length!==4}
function positionOptions(s){return[["center","中央"],["top","上"],["bottom","下"],["left","左"],["right","右"]].map(([v,l])=>`<option value="${v}"${s===v?" selected":""}>位置：${l}</option>`).join("")}
function dimensionsForRatio(r,l){const[a,b]=r.split(":").map(Number);return a>=b?{width:l,height:Math.round(l*b/a)}:{width:Math.round(l*a/b),height:l}}
function renderPreview(){if(state.photos.length===0){ui.previewCanvas.style.display="none";ui.emptyState.style.display="block";ui.outputInfo.textContent="4枚の写真を追加してください";return}const d=dimensionsForRatio(state.canvasRatio,1200);drawCollage(ui.previewCanvas,d.width,d.height);ui.previewCanvas.style.display="block";ui.emptyState.style.display="none";ui.outputInfo.textContent=`${state.canvasRatio} / ${d.width} × ${d.height}px preview / ${state.photos.length}枚`}
function getOutputDimensions(){if(state.exportLongEdge!=="original")return dimensionsForRatio(state.canvasRatio,+state.exportLongEdge);const m=Math.max(...state.photos.map(p=>Math.max(p.image.naturalWidth,p.image.naturalHeight)));return dimensionsForRatio(state.canvasRatio,Math.min(Math.max(m*2,2000),10000))}
function drawCollage(canvas,w,h){canvas.width=w;canvas.height=h;const c=canvas.getContext("2d",{alpha:false});c.fillStyle=state.backgroundColor;c.fillRect(0,0,w,h);const scale=Math.min(w,h)/1200,outer=Math.round(state.outerPadding*scale),gap=Math.round(state.gap*scale),radius=Math.round(state.cornerRadius*scale),aw=w-outer*2-gap,ah=h-outer*2-gap;let cols,rows;if(state.equalCells){cols=[Math.floor(aw/2),aw-Math.floor(aw/2)];rows=[Math.floor(ah/2),ah-Math.floor(ah/2)]}else{const tw=rowWeight(0,1),bw=rowWeight(2,3),lw=colWeight(0,2),rw=colWeight(1,3),th=clamp(Math.round(ah*tw/Math.max(tw+bw,.0001)),Math.round(ah*.28),Math.round(ah*.72)),lft=clamp(Math.round(aw*lw/Math.max(lw+rw,.0001)),Math.round(aw*.28),Math.round(aw*.72));rows=[th,ah-th];cols=[lft,aw-lft]}const cells=[{x:outer,y:outer,w:cols[0],h:rows[0]},{x:outer+cols[0]+gap,y:outer,w:cols[1],h:rows[0]},{x:outer,y:outer+rows[0]+gap,w:cols[0],h:rows[1]},{x:outer+cols[0]+gap,y:outer+rows[0]+gap,w:cols[1],h:rows[1]}];cells.forEach((cell,i)=>{const p=state.photos[i];p?drawPhoto(c,p,cell,radius):drawEmpty(c,cell,i)})}
function rowWeight(a,b){const v=[a,b].map(i=>state.photos[i]).filter(Boolean).map(p=>p.image.naturalHeight/p.image.naturalWidth);return v.length?v.reduce((x,y)=>x+y,0)/v.length:1}
function colWeight(a,b){const v=[a,b].map(i=>state.photos[i]).filter(Boolean).map(p=>p.image.naturalWidth/p.image.naturalHeight);return v.length?v.reduce((x,y)=>x+y,0)/v.length:1}
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
function drawEmpty(c,cell,i){c.save();c.fillStyle="rgba(127,127,127,.16)";c.fillRect(cell.x,cell.y,cell.w,cell.h);c.fillStyle="rgba(255,255,255,.38)";c.font=`${Math.max(18,Math.round(Math.min(cell.w,cell.h)*.09))}px -apple-system`;c.textAlign="center";c.textBaseline="middle";c.fillText(String(i+1),cell.x+cell.w/2,cell.y+cell.h/2);c.restore()}
function drawPhoto(c,p,cell,r){c.save();if(state.roundedCorners&&r>0){roundedRect(c,cell.x,cell.y,cell.w,cell.h,Math.min(r,cell.w/2,cell.h/2));c.clip()}const iw=p.image.naturalWidth,ih=p.image.naturalHeight,s=state.fitMode==="contain"?Math.min(cell.w/iw,cell.h/ih):Math.max(cell.w/iw,cell.h/ih),dw=iw*s,dh=ih*s,{xFactor,yFactor}=posFactor(p.position),dx=cell.x+(cell.w-dw)*xFactor,dy=cell.y+(cell.h-dh)*yFactor;if(state.fitMode==="contain"){c.fillStyle=state.backgroundColor;c.fillRect(cell.x,cell.y,cell.w,cell.h)}c.imageSmoothingEnabled=true;c.imageSmoothingQuality="high";c.drawImage(p.image,dx,dy,dw,dh);c.restore()}
function posFactor(p){switch(p){case"top":return{xFactor:.5,yFactor:0};case"bottom":return{xFactor:.5,yFactor:1};case"left":return{xFactor:0,yFactor:.5};case"right":return{xFactor:1,yFactor:.5};default:return{xFactor:.5,yFactor:.5}}}
function roundedRect(c,x,y,w,h,r){c.beginPath();c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r);c.closePath()}
async function downloadCollage(){if(state.photos.length!==4)return;ui.downloadButton.disabled=true;ui.downloadButton.textContent="書き出し中…";try{const d=getOutputDimensions(),canvas=document.createElement("canvas");drawCollage(canvas,d.width,d.height);const mime=state.exportFormat==="jpeg"?"image/jpeg":"image/png",q=state.exportFormat==="jpeg"?state.jpegQuality/100:undefined,blob=await new Promise((res,rej)=>canvas.toBlob(b=>b?res(b):rej(new Error("画像生成に失敗しました。")),mime,q)),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`four-photo-collage.${state.exportFormat==="jpeg"?"jpg":"png"}`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){alert(e.message)}finally{ui.downloadButton.disabled=false;ui.downloadButton.textContent="組み写真を保存"}}
async function loadDemo(){clearAll();const colors=[["#8799ad","#d8b9a0"],["#826f62","#d7cabd"],["#586a72","#aebec4"],["#3b454c","#b79c7c"]];for(let i=0;i<4;i++){const c=document.createElement("canvas");c.width=i%2===0?1400:1000;c.height=i%2===0?900:1300;const x=c.getContext("2d"),g=x.createLinearGradient(0,0,c.width,c.height);g.addColorStop(0,colors[i][0]);g.addColorStop(1,colors[i][1]);x.fillStyle=g;x.fillRect(0,0,c.width,c.height);x.fillStyle="rgba(255,255,255,.2)";x.beginPath();x.arc(c.width*.72,c.height*.28,Math.min(c.width,c.height)*.12,0,Math.PI*2);x.fill();x.fillStyle="rgba(20,20,22,.42)";x.fillRect(0,c.height*.67,c.width,c.height*.33);x.fillStyle="rgba(255,255,255,.75)";x.font=`700 ${Math.round(Math.min(c.width,c.height)*.12)}px -apple-system`;x.textAlign="center";x.textBaseline="middle";x.fillText(String(i+1),c.width/2,c.height/2);const blob=await new Promise(r=>c.toBlob(r,"image/png")),file=new File([blob],`demo-${i+1}.png`,{type:"image/png"});await addFiles([file])}}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
init();
